# Generated by Django 5.1.2 on 2024-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
